var countries = {
    "0": "Ba Cu - Trọn Đường[1[1.33",
    "1": "Bà Huyện Thanh Quan  -- Ba Huyen Thanh Quan[3[1", 
	"2": "Bà Triệu - (Lê Lợi - Yên Bái)  -- Ba Trieu[3[1",
	"3": "Bà Triệu - (Đoạn Yên Bái - Ba Cu)  -- Ba Trieu[4[1",
	"4": "Bà Triệu - (Đoạn Lê Lợi - Lê Ngọc Hân)  -- Ba Trieu[4[1",
	"5": "Bạch Đằng   --  Bach Dang[2[1",
	"6": "Bắc Sơn - (P.11)  -- Bac Son[4[1",
	"7": "Bến Đò (P.9)  -- Ben Do[4[1",
	"8": "Bến Nôm (P.Rạch Dừa)  -- Ben Nom[4[1",
	"9": "Bình Giã (Lê Hồng Phong - Hẻm 442)  -- Binh Gia[2[1",
	"10": "Bình Giã (Hẻm 442 - Đường 30/4)  -- Binh Gia[3[1",
	"11": "Cao Bá Quát - P. Rạch Dừa -- Cao Ba Quat[4[1",
	"12": "Cao Thằng -- Cao Thang[2[1",
	"13": "Chi Lăng - P.12  -- Chi Lang[4[1",
	"14": "Chu Mạnh Trinh -- Chu Manh Trinh[3[1",
	"15": "Cô Bắc -- Co Bac[3[1",
	"16": "Cô Giang - (Lê Lợi, Lê Ngọc Hân - Triệu Việt Vương) -- Co Giang[3[1",
	"17": "Dã Tượng (P. Thắng Tam) -- Da Tuong[3[1",
	"18": "Dương Vân Nga (P.Rạch Dừa) -- Duong Van Nga[4[1",
	"19": "Đào Duy Từ (P.Thắng Tam) -- Dao Duy Tu[3[1",
	"20": "Đinh Tiên Hoàng -- Dinh Tien Hoang[2[1",
	"21": "Đồ Chiểu (Lý Thường Kiệt - Lê Lai)-- Do Chieu[1[1.33",
	"22": "Đồ Chiểu (Lê Lai - Hẻm 114)-- Do Chieu[3[1",
	"23": "Đô Lương - P.11, P.12-- Do Luong[4[1",
	"24": "Đường 2 tháng 9 (2/9) Đoạn cuối quốc lộ 51B (Lê Hồng Phong - Nguyễn An Ninh)[1[1",
	"2444": "Đường 2 tháng 9 (2/9) Các tuyến đường 51B thuộc địa bàn phường 10, 11,12)[3[0.75",
	"25": "Đoàn Thị Điểm -- Doan Thi Diem[3[1",
	"26": "Đội Cấn (P.8) -- Doi Can[2[1",
	"27": "Đống Đa (P.Thắng Nhất, P.10) -- Dong Da[4[1",
	"28": "Đồng Khởi -- Dong Khoi[2[1",
	"29": "Đường 3/2 (Vòng Xoay Liệt Sĩ - 3/2) -- Duong 3/2[1[1",
	"39": "Đường 3/2 (3/2 - Vòng xoay đường 3/2 và trục đường 51B) -- Duong 3/2[3[1",
	"31": "Đường 30/4 (Ngã 4 Giếng nước - Ẹo Ông Từ ) -- Duong 30/4[2[1",
	"3111": "Các tuyến hẻm 61 đường 30/4 (khu nhà ở chính sách) -- Duong 30/4[4[1",
	"3112": "Đường D4, D5(phường 10) -- D4, D5[3[1",
	"3112": "D10 (phường 11) -- D10[3[0.75",
	"32": "Đường bờ kè Rạch Bến Đình (Dự án nhà ở đại An - Hết phần đất giao Công ty phát triển Nhà)[3[1",
	"33": "Đường D4 (P.10) - hết đường nhựa[3[1",
	"34": "Đường D5 (P.10) - hết đường nhựa[3[1",
	"35": "Đường lên biệt thự đồi sứ (Trần Phú - Nhà số 12/6A)[2[1",
	"36": "Đường lên biệt thự đồi sứ (Trần Phú - Nhánh đường lên Biệt thự Đồi Sứ)[3[1",
	"37": "Đường từ biệt thự 14,15 song song với đường Võ Thị Sáu đi ra khu biệt thự Công ty Phát triển nhà xây dựng[2[1",
	"38": "Đường vành đai khu tái định cư Bến Đình (P6) (Lê Văn Lộc - bờ kè Sông Bến Đình)[4[1",
	"39": "Đường vào Xí nghiệp Quyết Tiến[4[1",
	"40": "Đường ven biển Hải Đăng  (Đường 3/2 - Cầu Cửa Lấp)[3[1",
	"41": "Hạ Long -- Ha Long[1[1",
	"42": "Hải Đăng (Hạ Long - Số 5 Nhà nghỉ Long An cũ) -- Hai Dang[3[1",
	"43": "Hải Đăng (Số 5 Nhà nghỉ Long An cũ) - Đèn Hải Đăng -- Hai Dang[4[1",
	"44": "Hải Đăng (Ngã 3 - Tượng Chúa) -- Hai Dang[4[1",
	"45": "Hải Đăng (Hẻm Hải Đăng) -- Hai Dang[4[1",
	"46": "Hải Thượng Lãn Ông (P.Rạch Dừa) -- Hai Thuong Lan Ong[4[1",
	"47": "Hai tuyến đường nối từ đường Bình Giã vào khu chợ Rạch Dừa  (P.Rạch Dừa) (Bình Giã- Khu Chợ Rạch Dừa)[3[1",
	"48": "Hàn Mặc Tử (P.7) -- Han Mac Tu[3[1",
	"49": "Hàn Thuyên  (P.Rạch Dừa) -- Han Thuyen[4[1",
	"50": "Hẻm số 1 Nguyễn An Ninh -- Hem so 1 Nguyen An Ninh[4[1",
	"51": "Hẻm số 110 Phạm Hồng Thái (Phạm Hồng Thái - Ngô Đức Kế) - Pham Hong Thai[2[1",
	"52": "Hẻm 135 Lê Quang Định (P.Thắng Nhất) (gồm các đoạn đường nội bộ khu đất PTSC của Công ty Dịch vụ Dầu khí) - Le Quang Dinh[4[1",
	"53": "Hẻm  02, 04, 36, 50 Nguyễn Lương Bằng (P9) - Nguyen Luong Bang[3[1",
	"54": "Hẻm 30 Lương Thế Vinh (P9) -- Luong The Vinh[3[1",
	"55": "Hẻm 40 - Phan Đăng Lưu -- Phan Dang Luu[3[1",
	"56": "Hẻm  43, 61 đường Phạm Ngọc Thạch (P9) -- Pham Ngoc Thach[3[1",
	"57": "Hẻm 492 - đường 30/4 (P.Rạch Dừa) (Nối từ đường 30/4 - Khu chợ Rạch Dừa) -- duong 30/4[3[1",
	"58": "Hẻm 524 - đường 30/4 (P.Rạch Dừa) (Nối từ đường 30/4 - Khu chợ Rạch Dừa) -- duong 30/4[3[1",
	"59": "Hẻm 58 Nguyễn Gia Thiều -- Nguyen Gia Thieu[4[1",
	"60": "Hẻm 825 và 875 Bình Giã (P10) (đường vào khu tái định cư 4,1 ha) -- Binh Gia[4[1",
	"61": "Hồ Quý Ly -- Ho Quy Ly[3[1",
	"62": "Hồ Tri Tân (P.Rạch Dừa) -- Ho Tri Tan[4[1",
	"63": "Hồ Xuân Hương -- Ho Xuan Huong[3[1",
	"64": "Hoa Lư (P.12) -- Hoa Lu[4[1",
	"65": "Hoàng Diệu -- Hoang Dieu[1[1",
	"66": "Hoàng Hoa Thám (P.2, P.3, phường Thắng Tam) (Thùy Vân - Võ Thị Sáu) -- Hoang Hoa Tham[1[1.33",
	"67": "Hoàng Hoa Thám (Đoạn còn lại) -- Hoang Hoa Tham[1[1",
	"68": "Hoàng Văn Thụ (P.7) -- Hoang Van Thu[2[1",
	"69": "Hoàng Việt, phường 6 (Phước Lâm Tự cũ) -- Hoang Viet[4[1",
	"70": "Hùng Vương -- Hung Vuong[2[1",
	"71": "Huyền Trân Công Chúa -- Huyen Tran Cong Chua[2[1",
	"72": "Huỳnh Khương An -- Huynh Khuong An[3[1",
	"73": "Huỳnh Khương Ninh -- Huynh Khuong Ninh[3[1",
	"74": "Kha Vạn Cân (P.7) -- Kha Van Can[3[1",
	"75": "Kim Đồng  (P.Rạch Dừa) -- Kim Dong[4[1",
	"76": "Ký Con -- Ky Con[3[1",
	"77": "Kỳ Đồng -- Ky Dong[4[1",
	"78": "La Văn Cầu -- La Van Cau[2[1",
	"79": "Lạc Long Quân  (Võ Thị Sáu  - Hết phần đất giao Công ty Phát triển Nhà) -- Lac Long Quan[3[1",
	"80": "Lê Hoàn  (P.Rạch Dừa) -- Le Hoan[4[1",
	"81": "Lê Hồng Phong (Lê Lợi - Thùy Vân) -- Le Hong Phong[1[1",
	"82": "Lê Lai (Lê Quý Đôn - Thống Nhất) -- Le Lai[2[1",
	"83": "Lê Lai (Thống Nhất - Trương Công Định) -- Le Lai[3[1",
	"84": "Lê Lợi -- Le Loi[1[1",
	"85": "Lê Ngọc Hân (Trần Phú - Thủ Khoa Huân)  -- Le Ngoc Han[1[1",
	"86": "Lê Ngọc Hân (Thủ Khoa Huân - Bà Triệu) -- Le Ngoc Han[3[1",
	"87": "Lê Phụng Hiểu -- Le Phung Hieu[3[1",
	"88": "Lê Quang Định (Đường 30/4 - Bình Giã)  -- Le Quang Dinh[3[1",
	"89": "Lê Quý Đôn (Quang Trung - Ngã 5 Lê Quý Đôn - Lê Lợi - Thủ Khoa Huân) -- Le Quy Don[1[1",
	"90": "Lê Quý Đôn (Đoạn còn lại) -- Le Quy Don[2[1",
	"91": "Lê Thánh Tông  -- Le Thanh Tong[4[1",
	"92": "Lê Thị Riêng -- Le Thi Rieng[4[1",
	"93": "Lê Văn Lộc (Đường 30/4 - Lê Thị Riêng) -- Le Van Loc[3[1",
	"94": "Lê Văn Lộc (Lê Thị Riêng - Bờ kè rạch Bến Đình) -- Le Van Loc[4[1",
	"95": "Lê Văn Tám  -- Le Van Tam[2[1",
	"96": "Lương Thế Vinh -- Luong The Vinh[3[1",
	"97": "Lương Văn Can -- Luong Van Can[3[1",
	"98": "Lưu Chí Hiếu (P9, P10, P.Rạch Dừa, P.Thắng Nhất)  -- Luu Chi Hieu[4[1",
	"99": "Lưu Hữu Phước (P.Rạch Dừa, P.Thắng Nhất)  -- Luu Huu Phuoc[4[1",
	"100": "Lý Thái Tổ  (P.Rạch Dừa) -- Ly Thai To[4[1",
	"101": "Lý Thường Kiệt (Nguyễn Trường Tộ - Phạm Ngũ Lão) -- Ly Thuong Kiet[2[1",
	"102": "Lý Thường Kiệt (Phạm Ngũ Lão - Lê Quý Đôn)  -- Ly Thuong Kiet[1[1.33",
	"103": "Lý Thường Kiệt (Lê Quý Đôn - Bà Triệu) -- Ly Thuong Kiet[2[1",
	"104": "Lý Tự Trọng (Lê Lợi - Lê Lai)  -- Ly Tu Trong[1[1",
	"105": "Lý Tự Trọng (Lê Lai - Hẻm 45, 146 Lý Tự Trọng) -- Ly Tu Trong[2[1",
	"106": "Lý Tự Trọng (Đoạn còn lại) -- Ly Tu Trong[3[1",
	"107": "Mạc Đỉnh Chi -- Mac Dinh Chi[3[1",
	"108": "Mai Thúc Loan  (P.Rạch Dừa) -- Mai Thuc Loan[4[1",
	"109": "Nam Kỳ Khởi Nghĩa  -- Nam Ky Khoi Nghia[1[1",
	"110": "Ngô Đức Kế (Nguyễn An Ninh - Cao Thắng) -- Ngo Duc Ke[2[1",
	"111": "Ngô Đức Kế (Cao Thắng - Pasteur) -- Ngo Duc Ke[3[1",
	"112": "Ngô Đức Kế (Đoạn còn lại) -- Ngo Duc Ke[4[1",
	"113": "Ngô Quyền (P. Thắng Nhất, P.Rạch Dừa) (Nguyễn Hữu Cảnh - Nơ Trang Long) -- Ngo Quyen[3[1",
	"114": "Ngô Văn Huyền -- Ngo Van Huyen[2[1",
	"115": "Ngư Phủ -- Ngu Phu[4[1",
	"116": "Nguyễn An Ninh -- Nguyen An Ninh[1[1",
	"117": "Nguyễn Bảo (Tự do cũ) -- Nguyen Bao[4[1",
	"118": "Nguyễn Bỉnh Khiêm -- Nguyen Binh Khiem[2[1",
	"119": "Nguyễn Bửu (P.Thắng Tam) -- Nguyen Buu[3[1",
	"120": "Nguyễn Chí Thanh -- Nguyen Chi Thanh[2[1",
	"121": "Nguyễn Công Trứ -- Nguyen Cong Tru[4[1",
	"122": "Nguyễn Cư Trinh -- Nguyen Cu Trinh[3[1",
	"123": "Nguyễn Du (Quang Trung - Trần Hưng Đạo) -- Nguyen Du[1[1",
	"124": "Nguyễn Du (Trần Hưng Đạo - Trương Công Định) -- Nguyen Du[2[1",
	"125": "Nguyễn Gia Thiều (P.12)  -- Nguyen Gia Thieu[4[1",
	"126": "Nguyễn Hiền -- Nguyen Hien[4[1",
	"127": "Nguyễn Hới (P.8) -- Nguyen Hoi[3[1",
	"128": "Nguyễn Hữu Cảnh (đường 30 - Trường tiểu học Chí Linh)  -- Nguyen Huu Canh[3[1",
	"129": "Nguyễn Hữu Cảnh (Đoạn còn lại) -- Nguyen Huu Canh[4[1",
	"130": "Nguyễn Hữu Cầu -- Nguyen Huu Cau[2[1",
	"131": "Nguyễn Kim -- Nguyen Kim[3[1",
	"132": "Nguyễn Lương Bằng -- Nguyen Luong Bang[2[1",
	"133": "Nguyễn Thái Bình -- Nguyen Thai Binh[3[1",
	"134": "Nguyễn Thái Học (P.7) -- Nguyen Thai Hoc[1[1",
	"135": "Nguyễn Thiện Thuật (Lê Quang Định - Nguyễn Hữu Cảnh) -- Nguyen Thien Thuat[3[1",
	"136": "Nguyễn Thiện Thuật (Đoạn còn lại) -- Nguyen Thien Thuat[4[1",
	"137": "Nguyễn Trãi -- Nguyen Trai[1[1",
	"138": "Nguyễn Tri Phương (Ngô Đức Kế - Nhà số 40 và số 31)  -- Nguyen Tri Phuong[1[1",
	"139": "Nguyễn Tri Phương (Nhà số 40 và số 31 - Trương Công Định) -- Nguyen Tri Phuong[3[1",
	"140": "Nguyễn Trung Trực  -- Nguyen Trung Truc[3[1",
	"141": "Nguyễn Trường Tộ  -- Nguyen Truong To[2[1",
	"142": "Nguyễn Văn Cừ  -- Nguyen Van Cu[2[1",
	"143": "Nguyễn Văn Trỗi  -- Nguyen Van Troi[1[1.33",
	"144": "Nơ Trang Long (P.Rạch Dừa)  -- No Trang Long[3[1",
	"145": "Ông Ích Khiêm (Nối từ dự án nhà ở Đại An - Hết phần đất giao cho Công ty Phát triển nhà) -- Ong Ich Khiem[3[1",
	"146": "Pasteur[2[1",
	"147": "Phạm Cự Lạng (P.Rạch Dừa) -- Pham Cu Lang[4[1",
	"148": "Phạm Hồng Thái  -- Pham Hong Thai[2[1",
	"149": "Phạm Ngọc Thạch  -- Pham Ngoc Thach[2[1",
	"150": "Phạm Ngũ Lão  -- Pham Ngu Lao[3[1",
	"151": "Phạm Thế Hiển (Nam Kỳ Khởi Nghĩa  - Xô viết nghệ tĩnh)  -- Pham The Hien[3[1",
	"152": "Phạm Thế Hiển (Đoạn còn lại)  -- Pham The Hien[4[1",
	"153": "Phạm Văn Dinh -- Pham Van Dinh[4[1",
	"154": "Phạm Văn Nghị (P.Thắng Nhất) (Đoạn vuông góc với đường Lê Quang Định - Nguyễn Thiện Thuật) -- Pham Van Nghi[3[1",
	"155": "Phan Bội Châu -- Phan Boi Chau[2[1",
	"156": "Phan Chu Trinh (Thùy Vân - Võ Thị Sáu ) -- Phan Chu Trinh[1[1",
	"157": "Phan Chu Trinh (Ngã 3 Võ Thị Sáu - Đinh Tiên Hoàng) -- Phan Chu Trinh[2[1",
	"158": "Phan Đăng Lưu -- Phan Dang Luu[2[1",
	"159": "Phan Đình Phùng -- Phan Dinh Phung[1[1",
	"160": "Phan Kế Bính -- Phan Ke Binh[3[1",
	"161": "Phan Văn Trị -- Phan Van Tri[2[1",
	"162": "Phó Đức Chính -- Pho Duc Chinh[2[1",
	"163": "Phùng Khắc Khoan -- Phung Khac Khoan[2[1",
	"164": "Phước Thắng (P.12) -- Phuoc Thang[4[1",
	"165": "Quang Trung[1[1",
	"166": "Sương Nguyệt Ánh -- Suong Nguyet Anh[3[1",
	"167": "Tản Đà (Hai Bà Trưng cũ) (P.Rạch Dừa) -- Tan Da[4[1",
	"168": "Tăng Bạt Hổ -- Tang Bat Ho[4[1",
	"169": "Thắng Nhì -- Thang Nhi[4[1",
	"170": "Thi Sách -- Thi Sach[1[1",
	"171": "Thống Nhất (Quang Trung - Lê Lai) -- Thong Nhat[1[1",
	"172": "Thống Nhất (Lê Lai - Trương Công Định) -- Thong Nhat[2[1",
	"173": "Thủ Khoa Huân -- Thu Khoa Huan[1[1",
	"174": "Thùy Vân (P.2, P.8, P. Thắng Tam) -- Thuy Van[1[1.33",
	"175": "Tiền Cảng (Hẻm Quân Cảng cũ) -- Tien Cang[4[1",
	"176": "Tô Hiến Thành -- To Hien Thanh[3[1",
	"177": "Tôn Đản (P.Rạch Dừa) -- TOn Dan[4[1",
	"178": "2 đường Tôn Thất Thuyết, Trần Anh Tông -- Ton That Thuyet , Tran Anh Tong[4[1",
	"179": "Tôn Thất Tùng - Ton That Tung[2[1",
	"180": "Tống Duy Tân (P.9) (Lương Thế Vinh - Nguyễn Trung Trực)[4[1",
	"181": "Trần Bình Trọng -- Tran Binh Trong[3[1",	
	"182": "Trần Cao Vân -- Tran Cao Van[3[1",
	"183": "Trần Đồng -- Tran Dong[2[1",
	"184": "Trần Hưng Đạo -- Tran Hung Dao[1[1.33",
	"185": "Trần Nguyên Đán -- Tran Nguyen Dan[4[1",
	"186": "Trần Nguyên Hãn -- Tran Nguyen Han[2[1",
	"187": "Trần Phú (Quang Trung - Nhà số 46 Trần Phú) - Tran Phu[1[1",
	"188": "Trần Phú (Đoạn còn lại) -- Tran Phu[2[1",
	"189": "Trần Quốc Toản -- Tran Quoc Toan[4[1",
	"190": "Trần Quý Cáp -- Tran Quy Cap[2[1",
	"191": "Trương Công Định (Ngã 3 Hạ Long Quang Trung - Lê Lai) -- Truong Cong Dinh[2[1",
	"192": "Trương Công Định (Lê Lai - Ngã Năm)  -- Truong Cong Dinh[1[1",
	"193": "Trương Công Định (Ngã 5 - Nguyễn An Ninh) -- Truong Cong Dinh[1[1",
	"194": "Trương Công Định (Đoạn còn lại) -- Truong Cong Dinh[2[1",
	"195": "Trưng Nhị -- Trung Nhi[11.33",
	"196": "Trưng Trắc -- Trung Trac[1[1.33",
	"197": "Trương Hán Siêu (P.10) -- Truong Han Sieu[4[1",
	"198": "Trương Ngọc (P.Thắng Tam) -- Truong Ngoc[3[1",	
	"199": "Trương Văn Bang (P.7) -- Truong Van Bang[1[1",
	"200": "Trương Vĩnh Ký -- Truong Vinh Ky[1[1",
	"201": "Tú Xương - Tu Xuong[3[1",
	"202": "Tuệ Tĩnh (P.10) -- Tue Tinh[4[1",
	"203": "Tuyến đường nối vuông góc từ đường 30/4, có cùng độ rộng với  hẻm 524 (P.Rạch Dừa) (Nằm giữa hẻm 524 và đường Bình Giã  - Khu chợ Rạch Dừa)[3[1",
	"204": "Văn Cao (P.2) -- Van Cao[4[1",
	"205": "Vi Ba (Lê Lợi - Ngã 3 Vi Ba )[3[1",
	"206": "Vi Ba (gã 3 Vi Ba - Hẻm 105 Lê Lợi )[3[1",
	"207": "Vi Ba (Đoạn còn lại)[4[1",
	"208": "Võ Nguyên Giáp (Vòng xoay đường 3/2 và trục  - Ẹo Ông Từ) -- Vo Nguyen Giap[3[1",
	"209": "Võ Nguyên Giáp (Ẹo Ông Từ - CS Trung Tín (cầu Cây Khế cũ)) -- Vo Nguyen Giap[3[1",
	"210": "Võ Nguyên Giáp (CS Trung Tín (cầu Cây Khế cũ) - Hoa Lư) -- Vo Nguyen Giap[4[1",
	"211": "Võ Nguyên Giáp (Hoa Lư -- Cầu Cỏ May) -- Vo Nguyen Giap[3[1",
	"212": "Võ Thị Sáu -- Vo Thi Sau[2[1",
	"213": "Võ Văn Tần -- Vo Van Tan[4[1",
	"214": "Xô Viết Nghệ Tĩnh -- Xo Viet Nghe Tinh[2[1",
	"215": "Yên Bái - Yen Bai[3[1",
	"216": "Yên Đổ -- Yen Do[4[1",
	"217": "Yersin[2[1",
	"218": "Võ Đình Thành - Vo Dinh Thanh[3[1",
	"219": "khu nhà ở Á Châu - Rộng từ 5-7m (A Chau)[4[1",
	"220": "khu nhà ở Á Châu - Đường trục chính có lòng đường trải nhựa rộng 8m nối từ Hoàng Hoa Thám đến Phan Chu Trinh (A Chau)[3[1.25",
	"221": "khu nhà ở Á Châu - Tuyến đường vuông góc với tuyến trục chính có lòng đường trải nhựa lớn hơn 7,5m (A Chau)[3[1",
	"222": "Cống Hộp - Nguyễn Thị Minh Khai (Cong Hop - Nguyen Thi Minh Khai)[3[1",
	"223": "Trần Huy Liệu - Tran Huy Lieu[3[1",
	"224": "Trần Khánh Dư - Tran Khanh Du[3[1",
	"225": "Trần Khắc Chung - Tran Khac Chung[3[1",
	"226": "Hẻm 01, 03, 04, 05 Trần Khắc Chung - Tran Khac Chung[4[1",
	"227": "Con đường hình chữ U (phần kéo dài của đường Trần Khánh Dư có 2 nhánh nối vuông góc với đường Trần Huy Liệu - Tran Khanh Du [3[1",
	"228": "Những tuyến đường chưa có tên trong khu trung tâm thương mại phường 7 (Ngô Đức Kế - Nguyễn Thái Học - Trương Văn Bang)[2[1",
	"229": "Trần Xuân Độ -- Tran Xuan Do[4[1",
	"230": "Triệu Việt Vương -- Trieu Viet Vuong[3[1",
	"231": "Trịnh Hoài Đức (P.7) -- Trinh Hoai Duc[2[1",
	"232": "Phạm Hữu Lầu - Bình giã - Khu chợ Rạch Dừa[3[1",
	"233": "Phan Xích Long - Bình giã - Khu chợ Rạch Dừa[3[1",
	"234": "Hồ Đắc Di (hẻm 12 cũ Hoàng Hoa Thám (Nguyễn Trường Tộ - Dương Văn An) [3[1",
	"235": "Hồ Thị Kỷ (Hẻm 524 cũ đường 30/4)[3[1",
	"236": "Hẻm 05 Lê Hồng Phong (khu biệt thự Kim Minh, Kim Ngân)[2[1",
	"237": "Tạ Uyên [2[1",
	"238": "Trần Đình Xu (hẻm 492 cũ 30/4) [2[1",
	"239": "Trường Sa (P12) [4[1",
	"240": "Phan Huy Ích , Thái Văn Lung, đường Bàu Sen 1,2,3,5,7,9 [4[1",
	"241": "Phan Huy Chú [3[1",
	"242": "khu dân cư P9 - Lý Thái Tông (Trương Công Định - Lương Thế Vinh)-- Ly Thai Tong [3[1",
	"243": "khu dân cư P9 - Nguyễn Đức Thuận (Lương Thế Vinh - Lý Thái Tông) -- Nguyen Duc Thuan [3[1",
	"244": "khu dân cư P9 - Nguyễn Khang (Lương Thế Vinh - Lý Thái Tông) -- Nguyen Khang [3[1",
	"245": "Võ Trường Toản (Lương Thế Vinh nối dai) (Trần Cao Vân - Tôn Đức Thằng) -- Vo Truong Toan [3[1",
	"246": "Võ Trường Toản (Lương Thế Vinh nối dai) (Đường 30/4 - Trần Cao Vân) -- Vo Truong Toan [2[1",
	"247": "Lê Trọng Tấn (Trần Bình Trọng - Mai Xuân Thưởng) (Le Trong Tan) [4[1",
	"248": "Mai Xuân Thưởng (Nguyễn An Ninh - Trần Bình Trọng)[4[1",
	"249": "Nguyễn Hữu Thọ - (Nguyen Huu Tho) [4[1",
	"250": "(TTTM Phường 7) Bế Văn Đàn -- Be Van Dan[2[1",
	"251": "(TTTM Phường 7) Nam Cao, Nguyễn Kiệm, Nguyễn Oanh -- Nam Cao Nguyen Kiem, Nguyen Oanh[2[1",
	"252": "(TTTM Phường 7) Phùng Chí Kiên, Xuân Diệu, Xuân Thủy -- Phung Chi Kien, Xuan Dieu, Xuan Thuy [2[1",
	"253": "Lương Văn Nho ; Nguyễn Thị Định ; Tố Hữu -- Luong Van Nho ; Nguyen Thi Dinh ; To Huu[3[1",
	"254": "Ngô Tất Tố ; Ngô Gia Tự ; Nguyễn Bình ; Nguyễn Thị Thập -- Ngo Tat To ; Ngo Gia Tu ; Nguyen Binh ; Nguyen Thi Thap [4[1",
	"255": "Trần Quang Diệu -- Tran Quang Dieu [3[1",
	"256": "Tôn Đức Thắng ; Hồ Biểu Chánh -- Ton Duc Thang ; Ho Bieu Chanh [3[1",
	"257": "Nguyễn Thông ; Hàm Nghi ; Nguyễn Đức Cảnh - Nguyen Thong ; Ham Nghi, Nguyen Duc Canh [4[1",
	"258": "Nguyễn Phi Khanh -- Nguyen Phi Khanh [3[1",
	"259": "Nguyễn Bá Lân ; Hoàng Minh Giám -- Nguyen Ba Lan, Hoang Minh Giam[4[1",
	"260": "Dương Minh Châu ; Hoàng Trung Thông -- Duong Minh Chau, Hoan Trung Thong [4[1",
	
}